### ISSUE TITLE
Still Image Output

### ISSUE THREAD

**Issue by jbhav24** [aaronabentheuer/AAFaceDetection#5]
Hello, I love this! I recently implemented it into a app idea I've been playing around with but ran into an error. Does this not allow for stillimageoutputs? I need to be able to take a picture of the screen and have not found any solutions to this issue. 

I have a simple take photo function and it says that Visage does not have a imageOutput? What would be the steps to add this or just to have the basic functionality of taking a photo with this.

**Comment by meiirbek** [comment]
@jbhav24 Hi, have you solved your trouble?

**Comment by jbhav24** [comment]
@meiirbek Yes, I have. It isn't a perfect solution, but it is a solution.
